"use client";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { usePathname } from "next/navigation";
import Head from "next/head"; // Import Head component
import "./globals.css";
import Navbar from "@/components/Navbar";
import Navbar2 from "@/components/Navbar2";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const pathname = usePathname();

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Head>
          <title>{String(metadata.title)}</title> {/* Explicitly cast title */}
          <meta
            name="description"
            content={String(metadata.description)}
          />{" "}
          {/* Explicitly cast description */}
        </Head>
        <div className="flex-col flex overflow-x-hidden">
          {pathname === "/" ? <Navbar /> : <Navbar2 />}
          {children}
        </div>
      </body>
    </html>
  );
}
